sudo: required

language: python

services:
  - docker

before_install:
  - docker pull mwytock/epsilon

script:
  - docker run -v $HOME/epsilon:/epsilon mwytock/epsilon sh -c "cd /epsilon && python setup.py install && nosetests epsilon && make test"
